const USER_DOES_NOT_EXIST = "USER_DOES_NOT_EXIST"
const PASSWORD_IS_INCURRECT = "PASSWORD_IS_INCURRECT"
const ADDRESS_ALREADY_EXIST = "ADDRESS_ALREADY_EXIST"
const IMPORT_FAILED = "IMPORT_FAILED"
const OLDPWD_IS_INCURRECT = "OLDPWD_IS_INCURRECT"

const UNAUTHORIZATION = "UNAUTHORIZATION"
const REGISTER_INFO_IS_REQUIRED = "REGISTER_INFO_IS_REQUIRED"
const USER_ALREADY_EXIST = "USER_ALREADY_EXIST"
const ROLE_DOES_NOT_EXIST = "ROLE_DOES_NOT_EXIST"
const LOGIN_INFO_IS_REQUIRED = "LOGIN_INFO_IS_REQUIRED"
const NOPERMISSION = "NOPERMISSION"
const CATEGORY_ALREADY_EXIST = "CATEGORY_ALREADY_EXIST"
const CATEGORY_DOES_NOT_EXIST = "CATEGORY_DOES_NOT_EXIST"
const SERVICE_DOES_NOT_EXIST = "SERVICE_DOES_NOT_EXIST"

module.exports = {
  USER_DOES_NOT_EXIST,
  PASSWORD_IS_INCURRECT,
  ADDRESS_ALREADY_EXIST,
  IMPORT_FAILED,
  OLDPWD_IS_INCURRECT,
  
  UNAUTHORIZATION,
  REGISTER_INFO_IS_REQUIRED,
  USER_ALREADY_EXIST,
  ROLE_DOES_NOT_EXIST,
  LOGIN_INFO_IS_REQUIRED,
  NOPERMISSION,
  CATEGORY_ALREADY_EXIST,
  CATEGORY_DOES_NOT_EXIST,
  SERVICE_DOES_NOT_EXIST
}